# Codecov Configuration for SMPStats
# Validate at: https://codecov.io/validate

codecov:
  # Don't wait for CI to pass before sending notifications
  require_ci_to_pass: false
  notify:
    wait_for_ci: false

coverage:
  status:
    # Project coverage: checks overall coverage
    project:
      default:
        target: auto          # Compare to previous base commit
        threshold: 5%         # Allow 5% drop (tolerant for flaky tests)
        informational: true   # Don't block PRs, just inform
    
    # Patch coverage: checks new code only
    patch:
      default:
        target: 80%           # New code should be 80% covered
        threshold: 5%         # Allow some flexibility
        informational: true   # Don't block PRs initially

# Pull Request Comment Configuration
comment:
  layout: "header, diff, flags, files, footer"
  behavior: default
  require_changes: false      # Always show comment
  require_base: false         # Don't require base coverage
  require_head: true          # Require head coverage
  hide_project_coverage: false  # Show project coverage (not just diff)

# GitHub Check Run Annotations
github_checks:
  annotations: true  # Show inline coverage annotations (set to false if too noisy)
