name: SMPStats
version: 0.5.2
main: de.nurrobin.smpstats.SMPStats
api-version: '1.21'
author: nurrobin
description: Player statistics plugin for Paper 1.21.x SMP servers.
commands:
  stats:
    description: Zeigt SMPStats Statistiken.
    usage: /stats [player|json|dump]
  sstats:
    description: SMPStats Kurz-Command.
    usage: /sstats [info|reload|user <name> [reset|set <stat> <value>]]
    permission: smpstats.use
  smpstats:
    description: SMPStats Admin-Befehle.
    usage: /smpstats [info|reload|user <name> [reset|set <stat> <value>]]
    permission: smpstats.use
permissions:
  smpstats.reload:
    description: Erlaubt das Neuladen der SMPStats-Konfiguration.
    default: op
  smpstats.edit:
    description: Erlaubt das Setzen/Zurücksetzen von Spielerstats.
    default: op
  smpstats.use:
    description: Erlaubt Zugriff auf /sstats und /smpstats.
    default: true
