name: SMPStats
version: 0.13.0
main: de.nurrobin.smpstats.SMPStats
api-version: '1.21'
author: nurrobin
description: Player statistics plugin for Paper 1.21.x SMP servers.
commands:
  stats:
    description: Zeigt SMPStats Statistiken.
    usage: /stats [player|json|dump]
  sstats:
    description: SMPStats Kurz-Command.
    usage: /sstats [info|reload|user <name> [reset|set <stat> <value>]]
    permission: smpstats.use
  smpstats:
    description: SMPStats Admin-Befehle.
    usage: /smpstats [info|reload|user <name> [reset|set <stat> <value>]]
    permission: smpstats.use
permissions:
  smpstats.reload:
    description: Erlaubt das Neuladen der SMPStats-Konfiguration.
    default: op
  smpstats.edit:
    description: Erlaubt das Setzen/Zurücksetzen von Spielerstats.
    default: op
  smpstats.use:
    description: Erlaubt Zugriff auf /sstats und /smpstats.
    default: true
  smpstats.gui:
    description: Erlaubt Zugriff auf das GUI Menü (/sstats gui).
    default: true
  smpstats.gui.stats:
    description: Erlaubt das Anzeigen eigener Statistiken im GUI.
    default: true
  smpstats.gui.stats.others:
    description: Erlaubt das Anzeigen der Statistiken anderer Spieler.
    default: op
  smpstats.gui.leaderboard:
    description: Erlaubt Zugriff auf die Leaderboards im GUI.
    default: true
  smpstats.gui.health:
    description: Erlaubt Zugriff auf Server Health im GUI.
    default: op
  smpstats.gui.health.manage:
    description: Erlaubt das Töten von Entities und Teleportieren über das GUI.
    default: op
  smpstats.health:
    description: Erlaubt Zugriff auf Server Health Stats (Legacy, nutze smpstats.gui.health).
    default: op
  smpstats.admin:
    description: Voller Admin-Zugriff auf alle SMPStats Funktionen.
    default: op
    children:
      smpstats.reload: true
      smpstats.edit: true
      smpstats.gui: true
      smpstats.gui.stats: true
      smpstats.gui.stats.others: true
      smpstats.gui.leaderboard: true
      smpstats.gui.health: true
      smpstats.gui.health.manage: true
      smpstats.health: true
