name: SMPStats
version: 0.2.0
main: de.nurrobin.smpstats.SMPStats
api-version: '1.21'
author: nurrobin
description: Player statistics plugin for Paper 1.21.x SMP servers.
commands:
  stats:
    description: Zeigt SMPStats Statistiken.
    usage: /stats [player|json|dump]
  smpstats:
    description: SMPStats Admin-Befehle.
    usage: /smpstats reload
    permission: smpstats.reload
permissions:
  smpstats.reload:
    description: Erlaubt das Neuladen der SMPStats-Konfiguration.
    default: op
